sharetech/account/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_page, name='login_page'),
    path('painel/<int:pk>/', painel, name='painel'),
    path('painel/pass_change/<int:pk>/', pass_change, name='pass_change'),
    path('404/', error_404, name='error_404'),

]

sharetech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('sharetech.account.urls')),
    path('produto/', include('sharetech.produto.urls')),
    path('', include('sharetech.core.urls')),
    path('api/', include('sharetech.api.urls')),    
    path('rest-auth/', include('rest_auth.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/login copy.html
{% load static %}
{% load render_bundle from webpack_loader %} 
<html lang="en">
<head>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

  <div id = "app"> 
    <app> </app> 
</div> 
<!-- <div id="app">
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
      
          <!-- Icon -->
          <div class="fadeIn first">
            <p> Share Tech Login **** colocar algo aqui</p>
          </div>
      
          <!-- Login Form -->
          <form method="POST">
            {% csrf_token %}

            <input type="text" v-model:'$v.email.$model' id="email" class="fadeIn second" name="email" placeholder="E-mail">
            <p v-if='$v.email.$error'> Este e-mail é invalido</p>         
            <input type="password" v-model:'$v.name.password' id="password" class="fadeIn third" name="password" placeholder="Senha">           

            
            <p></p>
            <hr>
            <input type="submit"  value="Entrar">
          </form>
        
          <!--footer -->
          <div id="formFooter">   
            <p>Nao esta cadastrado? 
             <a href="{% url 'account:register' %}">Clique aqui!</a> 
            </p>                    
          </div>      
        </div>
    </div>
</div> -->


{% render_bundle 'app'%} 


</body>
</html>

templates/login.html
{% load static %}
{% load render_bundle from webpack_loader %} 
<html lang="en">
<head>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
  <div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <p> Share Tech Login **** colocar algo aqui</p>
      </div>
  
      <!-- Login Form -->
    <div id = "app"> 
      {% csrf_token %}
    </div>
<!--footer -->
<div id="formFooter">   
  <p>Nao esta cadastrado? 
   <a href="#">Clique aqui!</a> 
  </p>                    
</div>      
</div>
</div>
</div>

{% render_bundle 'app'%} 


</body>
</html>

templates/painel.html
{% extends 'index.html' %}
{% load static %}


{% block head %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'js/jquery.mask.js' %}" ></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<style>
    .flex-box {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 200px;
    }
</style>
{% endblock %}

{% block content %}
<!-- 
    {{ form.non_field_errors }}

    <hr>
    <h2 class="flex-box container-box">Painel de controle do usuário</h2>
    
    <div class="container">
    
    <div class="row">
    <div class="flex-box container-box" style="margin-left: 50px;">
        <form class="pure-form pure-form-aligned" method="POST">
        {% csrf_token %}
        {% for field in form %}         
            <fieldset>
                <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                </div>
                {% endfor %}
             
        <div class="row" style="margin-top: 30px; margin-left: 40px;"> 
        </fieldset></div>
 <div class="col">
            <button type='submit' class="btn btn-success btn-icon-split" style="margin-top: 25px;" >
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Salvar</span>
            </button>
        </form>
            <button type='submit' class="btn btn-warning btn-icon-split" style="margin-top: 25px;">
                <span class="icon text-white-50">
                    <i class="fas fa-check"></i>
                </span>
                <span class="text">Alterar senha</span>
            </button>
        </div>
    </div>
    </div> -->
                
<h2>Dados de Endereco</h2> </div>
            
<div id="app">
  <div class="container">
    <div class="row show-grid">
      <form class="col-md-12" v-on:submit.prevent="enviar_post">
        <h2>Auto Preenchimento de Endereço via CEP</h2>
        <div class="row">
          <div class="col-md-3">
            <div class="form-group">
              <label for="inputCep">CEP</label>
              <input class="form-control" id="inputCep" type="text" v-model="cep" v-on:keyup="buscar"/>
            </div>
          </div>
          <div class="col-md-3"><span class="text-danger" v-show="naoLocalizado"><strong>* CEP não encontrado</strong></span></div>
        </div>
        <div class="row">
          <div class="col-md-5">
            <div class="form-group">
              <label for="inputLogradouro">Logradouro</label>
              <input class="form-control" id="inputLogradouro" type="text" v-model="endereco.logradouro"/>
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group">
              <label for="inputNumero">Número</label>
              <input class="form-control" id="inputNumero" type="number" v-model="endereco.numero"/>
            </div>
          </div>
          <div class="col-md-5">
            <div class="form-group">
              <label for="inputComplemento">Complemento</label>
              <input class="form-control" id="inputComplemento" type="text" v-model="endereco.complemento"/>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5">
            <div class="form-group">
              <label for="inputBairro">Bairro</label>
              <input class="form-control" id="inputBairro" type="text" v-model="endereco.bairro"/>
            </div>
          </div>
          <div class="col-md-5">
            <div class="form-group">
              <label for="inputCidade">Cidade</label>
              <input class="form-control" id="inputCidade" type="text" v-model="endereco.localidade"/>
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group">
              <label for="inputEstado">Estado</label>
              <input class="form-control" id="inputEstado" type="text" v-model="endereco.uf" maxlength="2"/>
            </div>
          </div>
          <div class="col-md-2">
            <div class="form-group">
              <label for="inputFone">Telefone</label>
              <input class="form-control" id="inputFone" type="text" v-model="endereco.fone" maxlength="20"/>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-10"></div>
          <div class="col-md-2">
            <div class="form-group">
              <input class="form-control" type="submit" value="enviar"/>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>



<script src="{% static 'js/jquery.mask.js' %}" ></script>

<script>

var app = new Vue({
  el: '#app',
  data: {
    cep: '',
    endereco: {},
    naoLocalizado: false
  },
  mounted: function () {
    $("#inputCep").mask("00000-000");
  },
  methods: {
    registrar: function(){    
    },
    buscar: function(){
      var self = this;
      
      self.naoLocalizado = false;
      
      if(/^[0-9]{5}-[0-9]{3}$/.test(this.cep)){
        $.getJSON("https://viacep.com.br/ws/" + this.cep + "/json/", function(endereco){
          if(endereco.erro){
            self.endereco = {};
            $("#inputLogradouro").focus();
            self.naoLocalizado = true;
            return;
          }
          self.endereco = endereco;
          console.log(endereco);
          $("#inputNumero").focus();
        });
      }
    },
    enviar_post: function(){            
      axios.post('http://localhost:8000/account/painel/1/', {
        ...this.endereco
          },
          axios.defaults.xsrfCookieName = 'csrftoken',
          axios.defaults.xsrfHeaderName = "X-CSRFTOKEN")
          .then(function (response) {
            console.log(response);
          })
          .catch(function (error) {
            console.log(error);
            console.log(error.message);
          });
    },
  }
})  

</script>

{% endblock %}

templates/pass_change.html
{% extends 'index.html' %}
{% load static %}


{% block head %}
<script src="{% static 'js/jquery.mask.js' %}" ></script>

<style>
    .flex-box {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 200px;
    }

</style>
{% endblock %}

{% block content %}
{{ form.non_field_errors }}

<hr>
<h2 class="flex-box container-box">Alterar senha</h2>

<div class="container">

    {% if messages %}{% for mensagem in messages %}
                <a href="#" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text">{{mensagem}}</span>
                  </a>
    {% endfor %}
    {% endif %}

<div class="row">
<div class="flex-box container-box" style="margin-left: 50px;">
    <form class="pure-form pure-form-aligned" method="POST">
    {% csrf_token %}
    {% for field in form %}         
        <fieldset>
            <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            </div>
            {% endfor %}         

</div>
    <div class="col">
        <button type='submit' class="btn btn-success btn-icon-split" style="margin-top: 25px;">
            <span class="icon text-white-50">
                <i class="fas fa-check"></i>
            </span>
            <span class="text">Salvar</span>
        </button>
    </form>
    </div>
</div>
</div>


{% endblock %}

templates/register.html
{% load static %}
<html lang="en">
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
      
          <!-- Icon -->
          <div class="fadeIn first">
            <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
          </div>
      
          <!-- Login Form -->
          <form method="POST">
            {% csrf_token %}

            <input type="text" id="email" class="fadeIn second" name="email" placeholder="E-mail">
            <input type="text" id="username" class="fadeIn second" name="username" placeholder="Username">
            <input type="text" id="first_name" class="fadeIn second" name="first_name" placeholder="Nome">
            <input type="text" id="last_name" class="fadeIn second" name="last_name" placeholder="Sobrenome">
            <input type="password"id="password" class="fadeIn third" name="password" placeholder="Senha">
            <input type="password" id="password2" class="fadeIn third" name="password2" placeholder="Confirma senha" onkeyup='check();'>
            <span id='message'></span>
            
            <p></p>
            <input type="submit"  value="Registrar">
          </form>
      
          <!-- Remind Passowrd -->
          <div id="formFooter">                       
          </div>
      
        </div>
      </div>
    
<script>

  var check = function() {
    if (document.getElementById('password').value ==
      document.getElementById('password2').value) {
      document.getElementById('message').style.color = 'green';
      document.getElementById('message').innerHTML = 'Senhas válidas';
    } else {
      document.getElementById('message').style.color = 'red';
      document.getElementById('message').innerHTML = 'Senhas nao correspondem';
    }
  }

</script>


</body>
</html>